---
- name: create a empty directery and file
  hosts: all
  become: true
  remote_user: ansible
  tasks:
   - name: create directery
     file:
      path: /sample
      state: directory
      owner: root
      group: root
      mode: '0755'
   - name: create file
     file: 
      path: /sample/sree.txt
      state: touch
      owner: root
      group: root
      mode: '0644'
...