---
- name: demonstrate unarchive
  hosts: 192.168.1.99
  become: true
  remote_user: ansible
  tasks:
   - name: unarchive
     unarchive:
      src: /home/ansible/asiarchive.tar
      dest: /home/ansible/
      remote_src: yes
...
